import { describe, expect, it } from "bun:test"
import { defineTheme, defineThemes, generateTheme } from "../index"
import { dark, light, lightDark, twoLight, withReset } from "./fixtures/themes"
import { getBlock, parseDecls } from "./util"

describe("css generator > selectors", () => {
	it("emits a :root selector for the default theme", () => {
		const out = generateTheme(lightDark)
		expect(getBlock(out, ":root")).toBeString()
	})

	it("emits a selector for each theme", () => {
		const out = generateTheme(lightDark)
		expect(getBlock(out, ":root")).toBeString()
		expect(getBlock(out, ":root.dark")).toBeString()
	})

	it("ends every palette block with its color-scheme", () => {
		const out = generateTheme(lightDark)
		expect(getBlock(out, ":root")).toContain("color-scheme: light;")
		expect(getBlock(out, ":root.dark")).toContain("color-scheme: dark;")
	})
})

describe("css generator > token overrides", () => {
	it("emits constant tokens as literals in @theme", () => {
		const theme = parseDecls(getBlock(generateTheme(lightDark), "@theme"))
		expect(theme.get("--color-primary")).toBe("red")
		expect(theme.get("--color-secondary")).toBe("blue")
		expect(theme.get("--font-sans")).toBe("ui-sans-serif")
		expect(theme.get("--radius-md")).toBe("0.5rem")
	})

	it("promotes a varying token to a --th-* var referenced from @theme", () => {
		const out = generateTheme(lightDark)
		// @theme references the var rather than a literal…
		const theme = parseDecls(getBlock(out, "@theme"))
		expect(theme.get("--color-text")).toBe("var(--th-color-text)")
		// …with the base value in :root and the override in the other theme.
		expect(parseDecls(getBlock(out, ":root")).get("--th-color-text")).toBe("black")
		expect(parseDecls(getBlock(out, ":root.dark")).get("--th-color-text")).toBe("white")
	})

	it("does not promote constant tokens (no stray --th-* vars)", () => {
		const root = parseDecls(getBlock(generateTheme(lightDark), ":root"))
		expect(root.has("--th-color-primary")).toBe(false)
		expect(root.has("--th-radius-md")).toBe(false)
	})
})

describe("css generator > compound text namespace", () => {
	it("promotes each sub-prop independently (rem/line constant, weight varies)", () => {
		const out = generateTheme(lightDark)
		const theme = parseDecls(getBlock(out, "@theme"))
		// Constant sub-props stay literals…
		expect(theme.get("--text-sm")).toBe("1")
		expect(theme.get("--text-sm--line-height")).toBe("1.5")
		// …only the varying one is promoted.
		expect(theme.get("--text-sm--font-weight")).toBe("var(--th-text-sm-weight)")
		expect(parseDecls(getBlock(out, ":root")).get("--th-text-sm-weight")).toBe("400")
		expect(parseDecls(getBlock(out, ":root.dark")).get("--th-text-sm-weight")).toBe("700")
	})
})

describe("css generator > reset option", () => {
	it("emits no `initial` resets when reset is unset (fully additive)", () => {
		expect(generateTheme(lightDark)).not.toContain(": initial;")
	})

	it("emits `--<ns>-*: initial` only for listed namespaces", () => {
		const out = generateTheme(withReset)
		expect(out).toContain("--radius-*: initial;")
		expect(out).not.toContain("--color-*: initial;")
	})
})

describe("css generator > safelist", () => {
	it("emits @source inline for namespaces with a safelist prefix", () => {
		const out = generateTheme(lightDark)
		expect(out).toContain('@source inline("bg-{primary,secondary,text}");')
		expect(out).toContain('@source inline("text-{sm}");')
		expect(out).toContain('@source inline("rounded-{md}");')
	})

	it("emits nothing for safelist:null namespaces", () => {
		// `font` has tokens (font-sans) but safelist:null → no @source line.
		expect(generateTheme(lightDark)).not.toContain("font-{")
	})
})

describe("css generator > variants", () => {
	it("emits a custom-variant per scheme", () => {
		const out = generateTheme(lightDark)
		expect(out).toContain("@custom-variant is-light")
		expect(out).toContain("@custom-variant is-dark")
	})

	it("de-duplicates variants across same-scheme themes", () => {
		const out = generateTheme(twoLight)
		expect(out.match(/@custom-variant is-light/g)).toHaveLength(1)
		expect(out).not.toContain("is-dark")
	})
})

describe("css generator > structure", () => {
	it("includes the AUTO-GENERATED header", () => {
		expect(generateTheme(lightDark)).toContain("AUTO-GENERATED by twts")
	})

	it("skips namespaces no theme defines", () => {
		// `blur`, `shadow`, etc. are never defined by the fixture.
		expect(generateTheme(lightDark)).not.toContain("--blur-")
	})

	it("emits namespaces in registry order (color before text before radius)", () => {
		const theme = getBlock(generateTheme(lightDark), "@theme")
		const iColor = theme.indexOf("--color-")
		const iText = theme.indexOf("--text-")
		const iRadius = theme.indexOf("--radius-")
		expect(iColor).toBeLessThan(iText)
		expect(iText).toBeLessThan(iRadius)
	})

	it("leaves no dangling --th-* var (every reference has a :root definition)", () => {
		const out = generateTheme(lightDark)
		const referenced = [...out.matchAll(/var\((--th-[\w-]+)\)/g)].map((m) => m[1])
		const defined = new Set(parseDecls(getBlock(out, ":root")).keys())
		for (const v of referenced) expect(defined.has(v)).toBe(true)
	})

	it("is deterministic (same input → byte-identical output)", () => {
		expect(generateTheme(lightDark)).toBe(generateTheme(lightDark))
	})

	it("matches the light+dark snapshot", () => {
		expect(generateTheme(lightDark)).toMatchSnapshot()
	})
})

describe("css generator > error guards", () => {
	it("throws when no themes are defined", () => {
		expect(() => generateTheme(defineThemes([]))).toThrow("no themes defined")
	})

	it("throws when no theme is the default (none use :root)", () => {
		const a = defineTheme({ name: "a", scheme: "light", tokens: { color: { x: "red" } } })
		const b = defineTheme({ name: "b", scheme: "dark", tokens: { color: { x: "blue" } } })
		expect(() => generateTheme(defineThemes([a, b]))).toThrow("no default theme")
	})

	it("throws when more than one theme is the default", () => {
		expect(() => generateTheme(defineThemes([light, { ...dark, default: true }]))).toThrow(
			"more than one default theme"
		)
	})

	it("throws when a non-default theme uses a token missing from the default", () => {
		// `accent` exists only in the non-default theme → no base value to fall back to.
		const bad = defineTheme({
			name: "bad",
			scheme: "dark",
			tokens: { color: { primary: "red", secondary: "blue", text: "white", accent: "green" } },
		})
		expect(() => generateTheme(defineThemes([light, bad]))).toThrow("missing from the default theme")
	})
})
