import { afterEach, describe, expect, it } from "bun:test"
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { loadTokens, writeTheme } from "../node"

const modules = join(import.meta.dir, "fixtures", "modules")
const tmpDirs: string[] = []

function tmp() {
	const dir = mkdtempSync(join(tmpdir(), "twgen-test-"))
	tmpDirs.push(dir)
	return dir
}

afterEach(() => {
	for (const d of tmpDirs.splice(0)) rmSync(d, { recursive: true, force: true })
})

describe("loadTokens", () => {
	it("resolves a default export", async () => {
		const cfg = await loadTokens(join(modules, "default-export.ts"))
		expect(Object.keys(cfg.themes)).toEqual(["light", "dark"])
	})

	it("resolves a named `themes` export", async () => {
		const cfg = await loadTokens(join(modules, "named-export.ts"))
		expect(Object.keys(cfg.themes)).toEqual(["light", "dark"])
	})

	it("throws a helpful error when neither export is present", async () => {
		expect(loadTokens(join(modules, "neither-export.ts"))).rejects.toThrow("must export a defineThemes")
	})
})

describe("writeTheme", () => {
	it("returns true when the file is first created", async () => {
		const out = join(tmp(), "theme.gen.css")
		expect(await writeTheme(join(modules, "default-export.ts"), out)).toBe(true)
		expect(readFileSync(out, "utf8")).toContain("AUTO-GENERATED by twgen")
	})

	it("returns false when regenerating identical content", async () => {
		const out = join(tmp(), "theme.gen.css")
		await writeTheme(join(modules, "default-export.ts"), out)
		expect(await writeTheme(join(modules, "default-export.ts"), out)).toBe(false)
	})

	it("returns true when the on-disk content differs", async () => {
		const out = join(tmp(), "theme.gen.css")
		writeFileSync(out, "/* stale hand-edited content */")
		expect(await writeTheme(join(modules, "default-export.ts"), out)).toBe(true)
	})
})
